### ISSUE TITLE
`cobalt::race` doesn't ignore exception thrown by cancellation

### ISSUE THREAD

**Issue by Lyulf** [boostorg/cobalt#168]
When first awaitables processed by `cobalt::race` (or `cobalt::left_race`) is immediately ready then when the next awaitable is cancelled its exception is thrown directly on executor.
This doesn't happen when awaitables are processed in reverse order (tested using `cobalt::left_race`).

Tested on:
`Windows 10 64-bit using MSVC 17.9.0 (cl 19.39.33519 for x64)`

Example code:
```c++
#include <chrono>
#include <coroutine>
#include <iostream>

#include <boost/asio.hpp>
#include <boost/cobalt.hpp>

namespace asio = boost::asio;
namespace cobalt = boost::cobalt;

using namespace std::chrono_literals;

namespace
{

cobalt::promise<void> suspendUntilCancelled()
{
  asio::steady_timer timer{co_await cobalt::this_coro::executor};
  for (;;)
  {
    timer.expires_after(1s);
    co_await timer.async_wait(cobalt::use_op);
  }

}

cobalt::task<void> test()
{
  // Error doesn't happen when std::suspend_never is after suspendUntilCancelled
  co_await cobalt::left_race(std::suspend_never{}, suspendUntilCancelled());
}

} // namespace

int main(int /*argc*/, char** /*argv*/)
{
  asio::io_context context{1};

  auto future = cobalt::spawn(context.get_executor(), test(), asio::use_future);

  cobalt::this_thread::set_executor(context.get_executor());
  for (;;)
  {
    try
    {
      context.run();
      break;
    }
    catch (const std::exception& e)
    {
      std::cout << "context: " << e.what() << std::endl;
    }
  }

  try
  {
    future.get();
  }
  catch (const std::exception& e)
  {
    std::cout << "future: " << e.what() << std::endl;
  }

  std::cout << "Finished" << std::endl;

  return 0;
}
```

Output:
```
context: The I/O operation has been aborted because of either a thread exit or an application request [system:995]
Finished
```

**Comment by Lyulf** [comment]
After further analysis it seems that the conditions for this problem may be different than what I described.

Error happens 100% of the time for me when I test the above code but it seems to also happen under different conditions. In the code where I initially found the problem both awaitables are initially suspended and the second one resumes first but error still seems to happen.

Unfortunately I am currently unable to provide a second example because the error seems to depend on some external factors that I haven't yet figured out.

**Comment by Lyulf** [comment]
When fiddling with debugger I found that `receiver` in `cobalt_promise` is `NULL` when `unhandled_exception` is called.

**Comment by klemens-morgenstern** [comment]
This is the intended behaviour, however weird this particular case might be. I haven't really thought of this issue tbh.
I would be open to changing the specification if we find a better solution.

if you use `left_race` and the left-most argument is ready() (i.e. `await_ready` returns true), it will not consider any argument left of it. The same is true for select with it's random order.

What now happens is that the `left_select` returns without awaiting `suspendUntilCancelled`, which then goes out of scope. When it goes out of scope it detaches and cancels (hence the NULL for receiver). Since it's detached the exception caused by the cancellation must go somewhere, so it'll rethrow it from the main loop. I think in your case I would recommend this:

```cpp
cobalt::task<void> test()
{
  // Error doesn't happen when std::suspend_never is after suspendUntilCancelled
  auto s = suspendUntilCancelled();
  co_await cobalt::left_race(std::suspend_never{}, s);
  
  s.cancel();
  try {  co_await s; } catch(...) {}
  
}
```

Does my explanation make sense?

**Comment by Lyulf** [comment]
Thank you for the explanation. I tried the fix in my original code and it worked!

I can see why `cobalt::race` was implemented this way but current it is hard to use `cobalt::promise` with `cobalt::race` since every `cobalt::promise` would need to be cancelled and awaited given random nature of `cobalt::race`. At the same time I can see uses for awaiting results to differentiate thrown errors or if error was thrown at all. Maybe middle ground should be used and only rvalues should be awaited?

**Comment by Lyulf** [comment]
Maybe it is just a part of coroutines that requires getting used to.

There is even this line in documentation that I somehow missed:
`The race will invoke the functions of the awaitable as if used in a co_await expression or not evaluate them at all`

I think I will close this issue for now and reopen it or create a new one if I think of a good solution for this.
