### ISSUE TITLE
cobalt::channel does not work with move only type

### ISSUE THREAD

**Issue by dchansen** [boostorg/cobalt#183]
The channel class requires that the value type be copyable, so things like unique_ptrs cannot be used with it.

This example (for instance) does not compile:
```cpp

#include <boost/cobalt.hpp>
#include <any>
#include <memory>

namespace bc = boost::cobalt;

struct OnlyOne {
    OnlyOne() = default;
    OnlyOne(const OnlyOne&) = delete;
    OnlyOne( OnlyOne&&) = default;
};


bc::task<void> test(){
    bc::channel<OnlyOne> c;
    co_await c.write(OnlyOne());       
}


```
See [godbolt](https://godbolt.org/z/hW6rGz78K)

**Comment by klemens-morgenstern** [comment]
Thanks for reporting. I created fixes for both your issues, can you check if they fix all problems?

**Comment by dchansen** [comment]
Thanks for the quick response. Your patch fixed both issues.
