### ISSUE TITLE
boost 1.86 beta and cobalt shared library

### ISSUE THREAD

**Issue by bramasub1** [boostorg/cobalt#197]
Is the cobalt shared library not built anymore ?  I am using 

./b2 --prefix=/opt/boost_1_86 --reconfigure --with-python toolset=gcc cxxflags="-std=c++20 -O3"
./b2 install --prefix=/opt/boost_1_86_install

and I don't see it in the output.  My compiler is gcc12.3

**Comment by klemens-morgenstern** [comment]
Add --with-cobalt to your nuilf vommand

**Comment by bramasub1** [comment]
That worked.
