### ISSUE TITLE
Support `BOOST_ASIO_NO_TS_EXECUTORS` ?

### ISSUE THREAD

**Issue by Tradias** [boostorg/cobalt#214]
I honestly don't know what the story with this preprocessor macro in Asio is. Will it become the default, will it be removed, ... ?

Anyways this code:

https://github.com/boostorg/cobalt/blob/e69138f36bee13cb8f1bcb7a9f9c018add86b14d/include/boost/cobalt/detail/task.hpp#L315

makes use of `asio::bad_executor` which is guarded by it. See

https://github.com/boostorg/asio/blob/27b7596c335363ff4c8a83c26772f6737aff9dd4/include/boost/asio/executor.hpp#L20-L37

**Comment by klemens-morgenstern** [comment]
This all seems to be connected to the weird story around the executors TS. Are you using io_context::executor_type as executor?

**Comment by Tradias** [comment]
I am using https://github.com/Tradias/asio-grpc/blob/master/src/agrpc/grpc_executor.hpp whose implementation is very similar to `io_context::executor_type`.

Honestly I have no strong reason to define this macro. I just use it to get rid of some functionality that I shouldn't rely on since the executor TS appears to be superseded by sender/receiver.

**Comment by klemens-morgenstern** [comment]
Got it. It seems reasonable to support in cobalt, so I'll just change the exception type when the macro is defined.

I would be very interested in testing a cobalt setup with a third party executor, actually. I only used this for toy examples so far.

**Comment by Tradias** [comment]
My little test seems to compile now, thanks for the fix.

Now on to supporting MacOS😛

**Comment by klemens-morgenstern** [comment]
What's the MacOS issue?

**Comment by Tradias** [comment]
https://github.com/boostorg/cobalt/issues/179
