### ISSUE TITLE
Non-throwing channel::read and channel::write

### ISSUE THREAD

**Issue by anarthal** [boostorg/cobalt#76]
Would it be possible to have functions that don't throw, but return an error code, on cancellation?

**Comment by klemens-morgenstern** [comment]
There are a few solutions

1. overload that's non-throwing
2. make interrupt return a default constructed value if it's trivial
3. make all of async `system::result` aware.

**Comment by anarthal** [comment]
2. sounds bad. 1. and 3. sound better. 3. is the one that sounds best.

**Comment by klemens-morgenstern** [comment]
What's bad about (2) ? The value gets ignored anyhow, so a `channel<int>` could just return 0.

**Comment by anarthal** [comment]
2. seems to not cover default-constructible types, either, unless I'm missing something.

I'd go for `promise<result<T>> read(std::nothrow)` or similar.

**Comment by klemens-morgenstern** [comment]
Is this really a general issue or rather one concerning using channels in a `select` statement?

**Comment by anarthal** [comment]
In my case it was just with channels + select. I don't know enough about the library to say if this could happen under more situations.
